package commands

import (
	"context"
	"slices"
	"strings"
	"testing"
	"time"

	"eve-industry-planner/shared/models"
	eipmongo "eve-industry-planner/shared/mongo"
	"eve-industry-planner/shared/stackservices"
	"eve-industry-planner/testing/mongolive"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// The step reads jobs and archived jobs. A collection holding extras that is
// missing here keeps its category ids, and a statistics row derived from it
// carries the id in place of the name.
func TestJobCollectionsHoldingExtrasAreJobCollections(t *testing.T) {
	t.Parallel()
	for _, name := range []string{eipmongo.CollectionJobs, eipmongo.CollectionArchivedJobs} {
		if !slices.Contains(jobCollectionsHoldingExtras, name) {
			t.Fatalf("%s holds extras costs but is not read by the step", name)
		}
	}
	// Statistics rows are derived and regenerated by the rebuild, so stamping
	// them here would write labels the rebuild is about to overwrite.
	if slices.Contains(jobCollectionsHoldingExtras, eipmongo.CollectionStatisticsRows) {
		t.Fatal("statistics rows are derived and must not be stamped")
	}
}

const extrasDryRunScratchAccount = "eip-parity-extras-dryrun-account"

// A dry run is the operator's pre-flight, and it runs before the owner stamp.
// Reporting zero there is indistinguishable from having nothing to do, so the
// step has to name the stamp as the reason its filter matched nothing.
// Requires EIP_MONGO_PARITY_LIVE=1.
func TestExtrasDryRunRefusesWhenTheOwnerStampHasNotRun(t *testing.T) {
	mongo := mongolive.Require(t)
	mongolive.ScratchAccount(t, mongo, extrasDryRunScratchAccount)

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	settings := mongo.ApplicationSettings.Collection()
	if _, err := settings.UpdateByID(ctx, extrasDryRunScratchAccount, bson.M{"$set": bson.M{
		"extrasCategories": []bson.M{{"id": "7", "label": "Courier Contract"}},
	}}, options.UpdateOne().SetUpsert(true)); err != nil {
		t.Fatalf("seed settings: %v", err)
	}
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		_, _ = settings.DeleteOne(ctx, bson.M{"_id": extrasDryRunScratchAccount})
	})

	// An archived job carrying an extra whose category is named only in settings,
	// stamped with the account id but not yet with an owner: the state the window
	// opens in.
	job := bson.M{
		"_id": "extras-dryrun-job",
		"_meta": bson.M{
			"accountID": extrasDryRunScratchAccount,
		},
		"build": bson.M{"costs": bson.M{"extrasCosts": []bson.M{{"category": "7", "value": 100}}}},
	}
	if _, err := mongo.ArchivedJobs.Collection().InsertOne(ctx, job); err != nil {
		t.Fatalf("seed archived job: %v", err)
	}
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		_, _ = mongo.ArchivedJobs.Collection().DeleteOne(ctx, bson.M{"_id": "extras-dryrun-job"})
	})

	clients := &stackservices.Clients{Mongo: mongo}

	if _, err := stampExtrasCategoryLabels(ctx, clients, true); err == nil {
		t.Fatal("dry run reported success against a document with no owner")
	} else if !strings.Contains(err.Error(), "the owner stamp has not run") {
		t.Fatalf("dry run did not name the stamp: %v", err)
	}

	// Once stamped, the same dry run reports the work it would do.
	if _, err := mongo.ArchivedJobs.Collection().UpdateByID(ctx, "extras-dryrun-job", bson.M{"$set": bson.M{
		eipmongo.FieldMetaOwner: mongolive.OwnerDoc(models.AccountOwner(extrasDryRunScratchAccount)),
	}}); err != nil {
		t.Fatalf("stamp owner: %v", err)
	}

	report, err := stampExtrasCategoryLabels(ctx, clients, true)
	if err != nil {
		t.Fatalf("dry run after the stamp: %v", err)
	}
	if !strings.Contains(report, "would stamp 1 extra") {
		t.Fatalf("dry run did not report the work it would do: %s", report)
	}
}
